### ISSUE TITLE
Backwards Compatibility

### ISSUE THREAD

**Issue by netmanchris** [netmanchris/pyawair#12]
@danielsjf  Hit a snag - Looks like you're using the python variable annotations function which is available in Python 3.6.   

I just tried this out on a Python 3.5 box and was given a SyntaxError.   

Although I like the annotations, I don't see it as having enough value to prevent us from backwards compatibility.  

I haven't used this new feature though. Is there a specific reason that you used these in the objects module? I'm thinking of pulling them out to unbreak backwards compatibility but I wanted to discuss this before making the change. 

Is there a specific reason you added these in? What's the gain?

thanks!

Chris

**Comment by danielsjf** [comment]
Haha, they are only in because Pycharm likes it. No reason to keep them if it blocks anything else. You can remove them.

**Comment by netmanchris** [comment]
LOL Pycharm was the one throwing errrors too!   I’ll try and get the test suite worked out so that I can make sure changes don’t break anything and then we’ll start going after backwards compatibility as well.  

Closing.
