### ISSUE TITLE
Tests fail again

### ISSUE THREAD

**Issue by danielsjf** [netmanchris/pyawair#26]
@deanlyoung it seems that the test break again due to a change in the API. Everything works fine for my own API key, but when I use one of the test keys, it fails with the following message.

`Status code 404. Message: 'Could not decode Tier ENTERPRISE'.`

The problem can be reproduced with the following code.

```
from pyawair.auth import AwairAuth
from pyawair.objects import AwairDev
from pyawair.data import get_15_min_average

enterprise_dev = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiRFVNTVktRU5URVJQUklTRSJ9.bOM9rcABF9HKFHtxzF9kx8h9fv3CfvUIzveLFDRGrXs'

token = enterprise_dev

awair_auth = AwairAuth(token)
name = "Living room"
data = get_15_min_average(awair_auth,name)
```

The url:
`http://developer-apis.awair.is/v1/users/self/devices`

The headers:

```
{'Accept': 'application/json', 'Content-Type': 'application/json', 'Accept-encoding': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiRFVNTVktRU5URVJQUklTRSJ9.bOM9rcABF9HKFHtxzF9kx8h9fv3CfvUIzveLFDRGrXs'}
```

Do you know of any changes that might have caused this?

**Comment by deanlyoung** [comment]
Ahh, good catch!

**Comment by deanlyoung** [comment]
This should be resolved, thanks for reporting!

**Comment by danielsjf** [comment]
Perfect, it works again. Although it seems that some devices that we had hardcoded don't exist anymore. I'll change them.

**Comment by danielsjf** [comment]
Could it be that things also changed for the API and the timezone? Those tests also fail.

**Comment by danielsjf** [comment]
Alright, after some changes, all tests work again :-)
