### ISSUE TITLE
The average functions don't give the average

### ISSUE THREAD

**Issue by danielsjf** [netmanchris/pyawair#6]
I expected the 5 and 15 minute average data to give me the average of the last 5 and 15 minutes. This in contrast to the current data which can spike for some measurements like dust. Instead it seems to give me all the averages of the last month. This is more a problem of the Awair API, but maybe we could rename the function. Another idea is to add an argument for timeperiod which could have an unmodifiable  "last month" as default.

This is more to open a discussion.

**Comment by netmanchris** [comment]
@deanlyoung Any guidance here?  I haven’t had a chance to dive into the data returned by those APIs to be able to have a clear answer for this question.

**Comment by danielsjf** [comment]
I thought you might have an idea. Better to rely on the original Awair API documentation in this case. I'll read that before I give my opinion here. Could take a few days before I get to it.

**Comment by deanlyoung** [comment]
"/air-data/latest" is the only "/air-data/" endpoint that returns one result. The other 3 (raw, 5, & 15) all return up to 1000 results. You have optional parameters that you can comprise, such as a timestamp for start and end times/dates, "limit", and "desc". If you want these endpoints to behave like "/latest", then you have to specify "?limit=1"

**Comment by netmanchris** [comment]
Thanks @deanlyoung

@danielsjf I was thinking of adding in some ARGS to allow for better filtering of the results anyway based on what’s supported in the API, but if you have some thoughts about what you’d like to see, definitely let me know. 

I’ve got other clean up work to do so I can wait for your feedback.

**Comment by danielsjf** [comment]
So I use limit = 1 now, but it seems that there is actually a lag of half an hour. The values are not as 'actual' as 'latest'

**Comment by deanlyoung** [comment]
@danielsjf that’s probably due to the time it takes to compute averages for every individual device. It shouldn’t be 30 minutes, but it could be 15 for 15 minute averages (just a rule of thumb, not literal). And 5-10 minutes for 5 minute averages. How taxing would it be to compute your own averages based on maybe max limit=30 for a 5 minute average on the raw endpoint, or max limit=12 for like a 2 min. avg done via SDK instead of persisted in the database?

**Comment by danielsjf** [comment]
Yes, this is implemented now with the limit.
